### ISSUE TITLE
Vorp-inventory will not load script on Linux

### ISSUE THREAD

**Issue by Xh3ll** [VORPCORE/VORP-Inventory#51] opened 2022-02-02 18:56 UTC
Hello,

A couple of friends want to open a RedM server and have actually installed all the scripts from Vorp that are required so that the inventory is available, but they only get the following error message when they want to start the server:

```
[    c-scripting-core] Creating script environments for vorp_inventory
[         script:mono] System.Runtime.Remoting.RemotingException: Method 'SetConfiguration' not found in type 'CitizenFX.Core.InternalManager, CitizenFX.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
[         script:mono]
[         script:mono]
[         script:mono] Server stack trace:
[         script:mono]   at System.Runtime.Remoting.Messaging.CADMethodRef.Resolve () [0x0017f] in <9391d7651e69459eae268d8a1dfa670f>:0
[         script:mono]   at System.Runtime.Remoting.Messaging.CADMessageBase.GetMethod () [0x0000b] in <9391d7651e69459eae268d8a1dfa670f>:0
[         script:mono]   at System.Runtime.Remoting.Messaging.MethodCall..ctor (System.Runtime.Remoting.Messaging.CADMethodCallMessage msg) [0x0004b] in <9391d7651e69459eae268d8a1dfa670f>:0
[         script:mono]   at System.AppDomain.ProcessMessageInDomain (System.Byte[] arrRequest, System.Runtime.Remoting.Messaging.CADMethodCallMessage cadMsg, System.Byte[]& arrResponse, System.Runtime.Remoting.Messaging.CADMethodReturnMessage& cadMrm) [0x00012] in <9391d7651e69459eae268d8a1dfa670f>:0
[         script:mono]   at (wrapper remoting-invoke-with-check) System.AppDomain.ProcessMessageInDomain(byte[],System.Runtime.Remoting.Messaging.CADMethodCallMessage,byte[]&,System.Runtime.Remoting.Messaging.CADMethodReturnMessage&)
[         script:mono]   at System.Runtime.Remoting.Channels.CrossAppDomainSink.ProcessMessageInDomain (System.Byte[] arrRequest, System.Runtime.Remoting.Messaging.CADMethodCallMessage cadMsg) [0x0000d] in <9391d7651e69459eae268d8a1dfa670f>:0
[         script:mono]
[         script:mono] Exception rethrown at [0]:
[         script:mono]   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
[         script:mono]   at (wrapper remoting-invoke) CitizenFX.Core.InternalManager.SetConfiguration(bool)
[         script:mono]   at (wrapper xdomain-invoke) CitizenFX.Core.InternalManager.SetConfiguration(bool)
[         script:mono]   at (wrapper remoting-invoke-with-check) CitizenFX.Core.InternalManager.SetConfiguration(bool)
[         script:mono]   at CitizenFX.Core.MonoScriptRuntime.Create (CitizenFX.Core.IScriptHost host) [0x00105] in /src/code/client/clrcore/MonoScriptRuntime.cs:88
[                 Any] Error: Failed to create environment, hresult 80131501
Failed to create environment, hresult 80131501
```

if the script is removed, the server runs normally, but unfortunately without the inventory system

I hope that we could get a little food for thought as soon as possible so that we can eliminate this problem :D

Best regards

Xh3ll

**Comment by Local9** [comment] 2022-02-02 19:27
Which version are you using?

**Comment by Xh3ll** [comment] 2022-02-02 19:32
From Inventory? the latest release

**Comment by Local9** [comment] 2022-02-02 19:34
and which CFX Server build?

**Comment by Xh3ll** [comment] 2022-02-02 19:37
i tried in 5181 and the latest 5294 from CFX

**Comment by Local9** [comment] 2022-02-02 19:44
Could you try this really old files and let me know if it works.

[vorpinventory_old_files.zip](https://github.com/VORPCORE/VORP-Inventory/files/7989545/vorpinventory_old_files.zip)

**Comment by Xh3ll** [comment] 2022-02-02 19:48
Unfortunately no, the same problem persists

**Comment by Xh3ll** [comment] 2022-02-02 19:49
Unfortunately no, the same problem persists

**Comment by Local9** [comment] 2022-02-02 19:50
Ok, so least I know its not my changes... looks to be something with the CitizenFX.Core.dll not being updated

**Comment by Xh3ll** [comment] 2022-02-02 19:53
For example, if I run the same server files and such on my own Windows machine, everything works perfectly.

But as soon as I want to start the server on Linux, this error comes up immediately after loading the Vorp_inventory script

**Comment by Local9** [comment] 2022-02-02 19:56
Thats because mono isn't the same as Windows .NET, mono is rather behind on a lot of things, typical recommendation with CFX projects is to use Windows because of these edge cases.
[vorpinventory_sv.net.zip updated Nuget](https://github.com/VORPCORE/VORP-Inventory/files/7989613/vorpinventory_sv.net.zip)

If that file doesn't work, just for my own personal curiosity, put these in the folder, it may break in a different way, but I want to rule it out. They do not need to be added to the fxmanifest.
[CitizenFX.Core.Server.zip](https://github.com/VORPCORE/VORP-Inventory/files/7989620/CitizenFX.Core.Server.zip)

**Comment by Local9** [comment] 2022-02-02 19:59
Another thing that can be tried, is downloading the windows server files, grabbing the relevant dlls and seeing if replacing them does the trick. Pretty much just throwing things here as I don't have a linux box to test to try and iron out the issue.

**Comment by Xh3ll** [comment] 2022-02-02 20:13
At least it worked with the last Core.Server.DLL

Anyway, thank you so much for your help!

**Comment by Local9** [comment] 2022-02-02 20:14
So what happened? did you fix it? how did you fix it?

**Comment by Xh3ll** [comment] 2022-02-02 20:15
I deleted the other CitizenFX.Core.dll from server and i added the CitizenFX.Core.Server.dll from the last Zip you attached and now the server started up

**Comment by Local9** [comment] 2022-02-02 20:17
Thank you for letting me know :D as the issue is now corrected, I'll close the issue.

**Closed by Local9** 2022-02-02 20:17 UTC
